//
//  NGEnum.h
//  NaukriGulf
//
//  Created by Ayush Goel on 26/06/15.
//  Copyright (c) 2015 Infoedge. All rights reserved.
//

typedef NS_ENUM(NSInteger, DropDownConstants){
    DDC_COUNTRY = 0,
    DDC_CITY = 1,
    DDC_UGCOURSE = 2,
    DDC_UGSPEC = 3,
    DDC_PGCOURSE = 4,
    DDC_PGSPEC = 5,
    DDC_PPGCOURSE = 6,
    DDC_PPGSPEC = 7,
    DDC_EXP_MONTH = 8,
    DDC_WORK_LEVEL = 9,
    DDC_SALARY_LACS = 10,
    DDC_INDUSTRY_TYPE = 11,
    DDC_JOBTYPE = 12,
    DDC_PREFRENCE_LOCATION = 13,
    DDC_EMPLOYMENT_STATUS = 14,
    DDC_FAREA = 15,
    DDC_CURRENCY = 16,
    DDC_WORK_STATUS = 17,
    DDC_NATIONALITY = 18,
    DDC_NOTICE_PERIOD = 19,
    DDC_RELIGION = 20,
    DDC_MARITAL_STATUS = 21,
    DDC_EXP_YEARS = 22,
    DDC_LANGUAGE = 23,
    DDC_HIGHEST_EDUCTAION = 24,
    DDC_ALERT = 25,
    DDC_GENDER = 26,
    DDC_SALARY_RANGE = 27,
    DDC_LOCATION = 28,
    DD_EDIT_EXPERIENCE =104,
    DD_EDIT_COUNTRY_CITY = 105,
    DDC_DESIGNATION = 29,
    DDC_FAMAPPED = 30,
    DDC_COMPANY = 31,
    DDC_IAMAPPED = 32,

};


