//
//  GoogleAnalyticsConstant.h
//  NaukriGulf
//
//  Created by Arun Kumar on 23/12/13.
//  Copyright (c) 2013 Infoedge. All rights reserved.
//


extern NSString * const   K_GA_APP_LAUNCH_COUNT;
extern NSString * const   K_GA_HOME_SCREEN;
extern NSString * const   K_GA_FEEDBACK_SCREEN;
extern NSString * const   K_GA_SEARCH_RESULT_PAGE;
extern NSString * const   K_GA_SEARCH_SCREEN;
extern NSString * const   K_GA_MODIFY_ALERT_SCREEN;
extern NSString * const   K_GA_MNJ_SCREEN;
extern NSString * const   K_GA_MNJ_PROFILE_SCREEN;
extern NSString * const   K_GA_MNJ_SHORTLIST_SCREEN;
extern NSString * const   K_GA_MNJ_RECOMMENDED_JOB_SCREEN;
extern NSString * const   K_GA_MNJ_APPLIED_JOB_SCREEN;
extern NSString * const   K_GA_MNJ_CV;
extern NSString * const   K_GA_JD_WEB_JOB;
extern NSString * const   K_GA_JD_POSTED_JOB;
extern NSString * const   K_GA_APPLAY_FORM1_UNREG_SCREEN;
extern NSString * const   K_GA_APPLAY_FORM2_UNREG_EXPERIENCE_SCREEN;
extern NSString * const   K_GA_APPLAY_FORM2_UNREG_EDUCATION_SCREEN;
extern NSString * const   K_GA_APPLAY_UNREG_PREVIEW_SCREEN;
extern NSString * const   K_GA_WHATS_NEW_SCREEN;
extern NSString * const   K_GA_FORGOT_PASSWORD_SCREEN;
extern NSString * const   K_GA_APPLY_CONFIRMATION_SCREEN;
extern NSString * const   K_GA_REGISTER_SCREEN;
extern NSString * const   K_GA_JD_SIM_JOB;
extern NSString * const   K_GA_CVVIEWS_SCREEN_WATCH;




/// Resman
extern NSString * const   K_GA_RESMAN_CATEGORY;
extern NSString * const   K_GA_RESMAN_REGISTER;
extern NSString * const   K_GA_RESMAN_SOCIAL_REGISTER;

extern NSString * const   K_GA_RESMAN_EXP_OR_FRESHER;
extern NSString * const   K_GA_RESMAN_EDUCATION_FRESHER;
extern NSString * const   K_GA_RESMAN_SKILLS_FRESHER;
extern NSString * const   K_GA_RESMAN_LAST_STEP_FRESHER;
extern NSString * const   K_GA_RESMAN_RESUME_UPLOAD_FRESHER;
extern NSString * const   K_GA_RESMAN_CV_HEADLINE_FRESHER;
extern NSString * const   K_GA_RESMAN_PHOTO_UPLOAD_FRESHER;
extern NSString * const   K_GA_RESMAN_START_EXPLORING_FRESHER;
extern NSString * const   K_GA_RESMAN_JOB_PREFERENCES_FRESHER;
extern NSString * const   K_GA_RESMAN_VISA_DL_FRESHER;
extern NSString * const   K_GA_RESMAN_PERSONAL_DETAILS_FRESHER;

extern NSString * const   K_GA_RESMAN_WORK_EXP_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_INDUSTRY_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_SKILLS_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_LAST_STEP_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_RESUME_UPLOAD_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_CV_HEADLINE_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_PHOTO_UPLOAD_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_START_EXPLORING_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_JOB_PREFERENCES_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_VISA_DL_EXPERIENCED;
extern NSString * const  K_GA_RESMAN_PREV_EXP_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_EDUCATION_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_PERSONAL_DETAILS_EXPERIENCED;

extern NSString * const   K_GA_RESMAN_EVENT_RESUME_UPLOADED_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_EVENT_RESUME_UPLOADED_FRESHER;
extern NSString * const   K_GA_RESMAN_EVENT_CV_HEADLINES_EDITED_FRESHER;
extern NSString * const   K_GA_RESMAN_EVENT_PHOTO_UPLOADED_FRESHER;
extern NSString * const   K_GA_RESMAN_EVENT_START_JOB_SEARCH_FRESHER;
extern NSString * const   K_GA_RESMAN_EVENT_CV_HEADLINES_EDITED_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_EVENT_PHOTO_UPLOADED_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_EVENT_START_JOB_SEARCH_EXPERIENCED;
extern NSString * const   K_GA_RESMAN_EVENT_SKIP_PREV_EXP_EXPERIENCED;
extern NSString * const  K_GA_RESMAN_EVENT_SKIP_EDUCATION_EXPERIENCED;


extern NSString * const   K_GA_EVENT_CATEGORY ;
extern NSString * const   K_GA_EVENT_CATEGORY_SERVICE_CALL;
extern NSString * const  K_GA_EVENT_CATEGORY_APP_LAUNCH_COUNT ;
extern NSString * const  K_GA_EVENT_CATEGORY_PREDICTOR_SELECTION;


//Analytics event Names
extern NSString * const   K_GA_EVENT_APP_LAUNCH;
extern NSString * const   K_GA_EVENT_SEARCH_JOB;
extern NSString * const   K_GA_EVENT_PROFILE;
extern NSString * const   K_GA_EVENT_REFRESH_FORM;
extern NSString * const   K_GA_EVENT_RECENT_SEARCH;
extern NSString * const   K_GA_EVENT_SHORT_LISTED_JOB;
extern NSString * const   K_GA_EVENT_REFINE_SRP;
extern NSString * const   K_GA_EVENT_SAVE_ALERT;
extern NSString * const   K_GA_EVENT_MODIFIED_SAVE_ALERT;
extern NSString * const   K_GA_EVENT_EMAIL_WEB_JOB;
extern NSString * const   K_GA_EVENT_VIEW_ORINAL_WEB_JOB;
extern NSString * const  K_GA_EVENT_SEND_FEEDBACK;
extern NSString * const  K_GA_EVENT_EDIT_PROFILE ;
extern NSString * const  K_GA_EVENT_LOGOUT;
extern NSString * const   K_GA_EVENT_WATS_NEW;
extern NSString * const   K_GA_EVENT_REGISTER_FROM_LOGIN;
extern NSString * const   K_GA_EVENT_REGISTER_FROM_LOGIN_APPLY;
extern NSString * const   K_GA_EVENT_REGISTER_WITH_NG;
extern NSString * const  K_GA_EVENT_FEEDBACK_LIKE_IT;
extern NSString * const   K_GA_EVENT_FEEDBACK_IMPROVEMENT;
extern NSString * const   K_GA_EVENT_FEEDBACK_REMIND_ME;
extern NSString * const  K_GA_EVENT_CAREER_CAFE;
extern NSString * const K_GA_EVENT_FORCE_UPGRADE_CLICK;
extern NSString * const K_GA_EVENT_INDUSTRY_SELECTED;
extern NSString * const K_GA_EVENT_FA_SELECTED;
extern NSString * const K_GA_EVENT_PREDICTED_INDUSTRY_SELECTED;
extern NSString * const K_GA_EVENT_PREDICTED_FA_SELECTED;

// Analytics event label

extern NSString * const   K_GA_EVENT_SEARCH_JOB_LABEL;
extern NSString * const   K_GA_EVENT_NOTIFICATION_CATEGORY;
extern NSString * const  K_GA_EVENT_RECOMMENDED_JOBS_BACKGROUND_FETCH;

//background fetch tye GAs
extern NSString * const  K_GA_CATEGORY_BACKGROUNDFETCH;
extern NSString * const  K_GA_ACTION_BACKGROUNDFETCH_RECO_JOBS;
extern NSString * const K_GA_EVENT_BACKGROUNDFETCH_FAILED_NOTLOGGEDIN_USER;
extern NSString * const K_GA_EVENT_BACKGROUNDFETCH_FAILED_NIGHT_TIME;
extern NSString * const  K_GA_EVENT_BACKGROUNDFETCH_FAILED_SERVER_INTERVAL;
extern NSString * const K_GA_EVENT_BACKGROUNDFETCH_FAILED_BEFORE_INTERVAL_ACCESS;
extern NSString * const K_GA_EVENT_BACKGROUNDFETCH_FAILED_API_INVALID_RESPONSE;
extern NSString * const K_GA_EVENT_BACKGROUNDFETCH_FAILED_NETWORK_NOT_FOUND;

extern NSString * const  K_GA_EVENT_RECOMMENDED_JOB_NOTIFICATION;
extern NSString * const  K_GA_EVENT_RECOMMENDED_NOTIFICATION_CLICK;

//Resman notification GA
extern NSString * const K_GA_CATEGORY_RESMAN_NOTIFICATION;
extern NSString * const K_GA_ACTION_RESMAN_NOTIFICATION_GENERAL;
extern NSString * const K_GA_ACTION_RESMAN_NOTIFICATION_SET;
extern NSString * const K_GA_ACTION_RESMAN_NOTIFICATION_CLICK;

extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_SET_6_HOUR;
extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_SET_3_DAY;
extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_SET_7_DAY;
extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_SET_2_DAY_JOB_PREF;
extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_SET_2nd_WEEK_JOB_PREF;
extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_GENERAL_USER_REG_VIA_NOTIFICATION;
extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_GENERAL_USER_REG_ALREADY_REGISTERED;
extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_CLICK_6_HOUR;
extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_CLICK_3_DAY;
extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_CLICK_7_DAY;
extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_CLICK_2_DAY_JOB_PREF;
extern NSString * const K_GA_LABEL_RESMAN_NOTIFICATION_CLICK_2nd_WEEK_JOB_PREF;


// Local Notifications for Profile and user Engagement
extern NSString * const K_GA_LOCAL_NOTIFICATION_ACTION_PROFILE;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_SET_UPLOAD_PROFILE_PIC_2_DAY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CANCEL_UPLOAD_PROFILE_PIC_2_DAY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CLICK_UPLOAD_PROFILE_PIC_2_DAY;


extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_SET_UPLOAD_PROFILE_PIC_MONTHLY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CANCEL_UPLOAD_PROFILE_PIC_MONTHLY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CLICK_UPLOAD_PROFILE_PIC_MONTHLY;



extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_SET_EDIT_CV_1_DAY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CANCEL_EDIT_CV_1_DAY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CLICK_EDIT_CV_1_DAY;

extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_SET_EDIT_CV_MONTHLY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CANCEL_EDIT_CV_MONTHLY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CLICK_EDIT_CV_MONTHLY;


extern NSString * const K_GA_LOCAL_NOTIFICATION_ACTION_USER_ENGAGEMENT;

extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_SET_NON_LOGGEDIN_USER_12_HOUR;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CANCEL_NON_LOGGEDIN_USER_12_HOUR;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CLICK_NON_LOGGEDIN_USER_12_HOUR;

extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_SET_NON_LOGGEDIN_USER_WEEKLY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CANCEL_NON_LOGGEDIN_USER_WEEKLY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CLICK_NON_LOGGEDIN_USER_WEEKLY;


//This GA has monthly repeating alerts only
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_SET_LOGGEDIN_INACTIVE_USER_MONTHLY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CANCEL_LOGGEDIN_INACTIVE_USER_MONTHLY;
extern NSString * const K_GA_LOCAL_NOTIFICATION_LABEL_CLICK_LOGGEDIN_INACTIVE_USER_MONTHLY;


extern NSString * const K_GA_CATEGORY_UNREG;
extern NSString * const K_GA_ACTION_UNREG_APPLY;
extern NSString * const K_GA_LABEL_UNREG_APPLY;
extern NSString * const K_GA_RESMAN_COMPLETION_POST_UNREG;
extern NSString * const K_GA_CATEGORY_UNREG_MAILERS;

extern NSString * const K_GA_RESMAN_LANDING_FROM_MAILERS;
extern NSString * const K_GA_REGISTRATION_FROM_MAILERS;


extern NSString * const K_GA_VIEW_MORE_SIM_JOBS_RESULT_PAGE;

extern NSString * const K_GA_CATEGORY_LOGGED_IN;
extern NSString * const K_GA_ACTION_LOGGED_IN_APPLY;
extern NSString * const K_GA_SUCCESS_COUNT_APPLY;
extern NSString * const K_GA_ACTION_SPOTLIGHT;
extern NSString * const K_GA_ACTION_SPOTLIGHT_LAND;
extern NSString * const K_GA_ACTION_JDSIMJOB_LOGGED_IN_APPLY;
extern NSString * const K_GA_ACTION_JDSIMJOB_NON_LOGGED_IN_APPLY;

extern NSString * const K_GA_CATEGORY_APPLE_WATCH;
extern NSString * const K_GA_RECO_NOTIFICATION_RECIEVED;
extern NSString * const K_GA_OTHER_NOTIFICATION_RECIEVED;
extern NSString * const K_GA_APPLY_FROM_WATCH;
extern NSString * const K_GA_SAVE_FROM_WATCH;
extern NSString * const K_GA_OPTION_SCREEN_WATCH;
extern NSString * const K_GA_RECO_SCREEN_WATCH;
extern NSString * const K_GA_SAVED_SCREEN_WATCH;
extern NSString * const K_GA_NOTIFICATION_CLICKED_WATCH;

//3D TOUCH
extern NSString * const K_GA_EVENT_FORCE_TOUCH;
extern NSString *const K_GA_EVENT_FORCE_TOUCH_CLICK;
extern NSString * const K_GA_EVENT_FORCE_TOUCH;
extern NSString *const K_GA_EVENT_SHORTCUT_CV_VIEWED;
extern NSString *const K_GA_EVENT_SHORTCUT_SEARCH_JOBS;
extern NSString *const K_GA_EVENT_SHORTCUT_RECO_JOBS;
extern NSString *const K_GA_EVENT_SHORTCUT_SHORTLISTED_JOBS;

#pragma mark apple watch
extern NSString *const K_GA_JD_SCREEN;

