//
//  ServiceConstant.h
//  NaukriGulf
//
//  Created by Arun Kumar on 23/12/13.
//  Copyright (c) 2013 Infoedge. All rights reserved.
//


/********* API URL ***************/


//Constants from Naukri

enum BaseURLType {
    
    K_BASE_URL_JOB_SEARCH = 0,
    K_BASE_URL_LOGIN,
    K_BASE_URL_FILE_UPLOAD,
    K_BASE_URL_NEW_MONK

};

enum ServiceType {
    
    SERVICE_TYPE_ALL_JOBS = 0,
    SERVICE_TYPE_SSA =1,
    SERVICE_TYPE_JD =2,
    SERVICE_TYPE_RECENT_SEARCH_COUNT =3,
    SERVICE_TYPE_EMAIL_JOB =4,
    SERVICE_TYPE_FEEDBACK =5,
    SERVICE_TYPE_MODIFY_SSA = 6,
    SERVICE_TYPE_CUSTOM_QUESTION =7,
    SERVICE_TYPE_LOGIN = 8,
    SERVICE_TYPE_UPDATE_INFO_NOTIFICATION = 9,
    SERVICE_TYPE_RECOMMENDED_JOBS =10,
    SERVICE_TYPE_USER_DETAILS = 11,
    SERVICE_TYPE_LOGOUT =12,
    SERVICE_TYPE_UNREG_APPLY =13,
    SERVICE_TYPE_LOGGED_IN_APPLY = 14,
    SERVICE_TYPE_APPLIED_JOBS = 15,
    SERVICE_TYPE_WHO_VIEWED_MY_CV = 16,
    SERVICE_TYPE_GET_NOTIFICATION =17,
    SERVICE_TYPE_RESET_NOTIFICATION =18,
    SERVICE_TYPE_DELETE_PUSH_COUNT =19,
    SERVICE_TYPE_UPDATE_RESUME = 20,
    SERVICE_TYPE_DELETE_RESUME =21,
    SERVICE_TYPE_MNJ_INCOMPLETE_SECTION =22,
    SERVICE_TYPE_SIM_JOBS_PAGINATION = 23,
    SERVICE_TYPE_FORGET_PASSWORD = 24,
    SERVICE_TYPE_CHECK_REGISTERED_USER = 25,
    SERVICE_TYPE_MIS_JD = 26,
    SERVICE_TYPE_PROFILE_PHOTO = 27,
    SERVICE_TYPE_UPLOAD_PHOTO = 28,
    SERVICE_TYPE_ERROR_LOGGING =29,
    SERVICE_TYPE_DELETE_PHOTO =30,
    SERVICE_TYPE_EXCHANGE_TOKEN= 31,
    SERVICE_TYPE_APP_BLOCKER = 32,
    SERVICE_TYPE_SETTINGS = 33,
    SERVICE_TYPE_USER_REGISTERATION = 34,
    SERVICE_TYPE_UPLOAD_RESUME = 35,
    SERVICE_TYPE_DOWNLOAD_RESUME = 36,
    SERVICE_TYPE_CV_REMIND_ME_LATER = 37,
    SERVICE_TYPE_LOG_USER_ACTION = 38,
    SERVICE_TYPE_FILE_UPLOAD = 39,
    SERVICE_TYPE_DROPDOWN = 40,
    SERVICE_TYPE_USER_ACTIVE_STATE = 41,

};


enum RequestMethodType {
    
    K_REQUEST_METHOD_GET = 0,
    K_REQUEST_METHOD_POST,
    K_REQUEST_METHOD_DELETE,
    K_REQUEST_METHOD_PATCH,
    K_REQUEST_METHOD_PUT
};
enum ResponseCode{
    
    K_RESPONSE_SUCCESS = 200,
    K_RESPONSE_SUCESS_WITHOUT_BODY = 204,
    K_RESPONSE_CREATE_SUCCESS =201,
    K_RESPONSE_ERROR = 400,
    K_RESPONSE_AUTH_TOKEN_EXPIRED_ERROR = 401,
    K_RESPONSE_VALIDATION_ERROR = 403,
    K_RESPONSE_LOGIN_ERROR = 500,
    K_RESPONSE_IP_BLOCK_ERROR1 = 412,
    K_RESPONSE_IP_BLOCK_ERROR2 = 417,

    
};
enum SubResponseCode{
    
    K_SUBRESPONSE_VALIDATION_ERROR = 2004,
    
    
};
enum ResponseBodyType{
    
    RESPONSE_BODY_TYPE_WITH_BODY,
    RESPONSE_BODY_TYPE_WITHOUT_BODY,
    
};
enum JsonType{
    
    K_JSON_TYPE_VALID,
    K_JSON_TYPE_INVALID,
    
};




