platform :ios, '7.0'

target 'NaukriGulf' do
pod 'XcodeCoverage', '~>1.0'
pod 'MobileAppTracker'
pod 'GoogleAnalytics'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'GoogleConversionTracking', '~> 3.2'
pod 'GoogleSignIn'
plugin 'slather'

end
target 'NaukriGulfTestsCases' do
end
